/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) narx_disc_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 4, 7};
static const casadi_int casadi_s1[3] = {72, 1, 1};
static const casadi_int casadi_s2[3] = {2, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[3] = {4, 1, 1};
static const casadi_int casadi_s6[16] = 
  {74, 4, 0, 1, 4, 7, 9, 2,
  0, 1, 3, 0, 1, 4, 0, 1};
static const casadi_int casadi_s7[3] = {4, 0, 1};

static const casadi_real casadi_zeros[72] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* narx_disc_cost_y_fun_jac_ut_xt:(i0[72],i1[2],i2[0],i3[],i4[2])->(o0[4],o1[74x4,9nz],o2[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w02, *w03=w+74, w04, *w05=w+77, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, *w18=w+91, *w19=w+100, *w20=w+171, *w21=w+241, *w23=w+245, *w24=w+248;
  const casadi_int *cii;
  const casadi_real *cs, *wr01;
  /* #0: @0 = 2.23607 */
  w00 = 2.2360679774997898e+00;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[0] */
  w02 = wr01[0];
  /* #3: @3 = input[4][0] */
  casadi_copy(arg[4], 2, w03);
  /* #4: @4 = @3[0] */
  for (rr=(&w04), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #7: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #8: @2 = 0.316228 */
  w02 = 3.1622776601683794e-01;
  /* #9: @4 = 0.7 */
  w04 = 6.9999999999999996e-01;
  /* #10: @5 = input[1][0] */
  casadi_copy(arg[1], 2, w05);
  /* #11: @6 = @5[0] */
  for (rr=(&w06), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #12: @7 = 0 */
  w07 = 0.;
  /* #13: @8 = fmax(@6,@7) */
  w08  = casadi_fmax(w06,w07);
  /* #14: @9 = 1 */
  w09 = 1.;
  /* #15: @10 = fmin(@8,@9) */
  w10  = casadi_fmin(w08,w09);
  /* #16: @11 = @5[1] */
  for (rr=(&w11), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #17: @12 = fmax(@11,@7) */
  w12  = casadi_fmax(w11,w07);
  /* #18: @13 = fmin(@12,@9) */
  w13  = casadi_fmin(w12,w09);
  /* #19: @14 = (@10+@13) */
  w14  = (w10+w13);
  /* #20: @14 = (@4*@14) */
  w14  = (w04*w14);
  /* #21: @15 = @1[1] */
  w15 = wr01[1];
  /* #22: @15 = (@14-@15) */
  w15  = (w14-w15);
  /* #23: @15 = (@2*@15) */
  w15  = (w02*w15);
  /* #24: output[0][1] = @15 */
  if (res[0]) res[0][1] = w15;
  /* #25: @10 = (@10-@13) */
  w10 -= w13;
  /* #26: @10 = (@4*@10) */
  w10  = (w04*w10);
  /* #27: @13 = @1[2] */
  w13 = wr01[2];
  /* #28: @10 = (@10-@13) */
  w10 -= w13;
  /* #29: @10 = (@2*@10) */
  w10  = (w02*w10);
  /* #30: output[0][2] = @10 */
  if (res[0]) res[0][2] = w10;
  /* #31: @10 = -0.000431337 */
  w10 = -4.3133721733220226e-04;
  /* #32: @13 = -0.00299963 */
  w13 = -2.9996288193116886e-03;
  /* #33: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #34: @10 = (@10+@15) */
  w10 += w15;
  /* #35: @15 = -0.00719408 */
  w15 = -7.1940846644190657e-03;
  /* #36: @16 = (@15*@14) */
  w16  = (w15*w14);
  /* #37: @17 = (@16*@14) */
  w17  = (w16*w14);
  /* #38: @10 = (@10+@17) */
  w10 += w17;
  /* #39: @17 = @3[1] */
  for (rr=(&w17), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #40: @10 = (@10-@17) */
  w10 -= w17;
  /* #41: @10 = (@2*@10) */
  w10  = (w02*w10);
  /* #42: output[0][3] = @10 */
  if (res[0]) res[0][3] = w10;
  /* #43: @18 = zeros(74x4,9nz) */
  casadi_clear(w18, 9);
  /* #44: @19 = ones(74x1,71nz) */
  casadi_fill(w19, 71, 1.);
  /* #45: {@10, @20} = vertsplit(@19) */
  w10 = w19[0];
  casadi_copy(w19+1, 70, w20);
  /* #46: @17 = @20[0] */
  for (rr=(&w17), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #47: @0 = (@0*@17) */
  w00 *= w17;
  /* #48: @17 = (@8<=@9) */
  w17  = (w08<=w09);
  /* #49: @8 = (@9<=@8) */
  w08  = (w09<=w08);
  /* #50: @8 = (@17+@8) */
  w08  = (w17+w08);
  /* #51: @17 = (@17/@8) */
  w17 /= w08;
  /* #52: @8 = (@7<=@6) */
  w08  = (w07<=w06);
  /* #53: @6 = (@6<=@7) */
  w06  = (w06<=w07);
  /* #54: @6 = (@8+@6) */
  w06  = (w08+w06);
  /* #55: @8 = (@8/@6) */
  w08 /= w06;
  /* #56: @6 = @10[0] */
  for (rr=(&w06), cs=(&w10)+0; cs!=(&w10)+1; cs+=1) *rr++ = *cs;
  /* #57: @8 = (@8*@6) */
  w08 *= w06;
  /* #58: @17 = (@17*@8) */
  w17 *= w08;
  /* #59: @17 = (@4*@17) */
  w17  = (w04*w17);
  /* #60: @8 = (@2*@17) */
  w08  = (w02*w17);
  /* #61: @6 = (@13*@17) */
  w06  = (w13*w17);
  /* #62: @10 = (@15*@17) */
  w10  = (w15*w17);
  /* #63: @10 = (@14*@10) */
  w10  = (w14*w10);
  /* #64: @17 = (@16*@17) */
  w17  = (w16*w17);
  /* #65: @10 = (@10+@17) */
  w10 += w17;
  /* #66: @6 = (@6+@10) */
  w06 += w10;
  /* #67: @6 = (@2*@6) */
  w06  = (w02*w06);
  /* #68: @21 = vertcat(@0, @8, @8, @6) */
  rr=w21;
  *rr++ = w00;
  *rr++ = w08;
  *rr++ = w08;
  *rr++ = w06;
  /* #69: (@18[0, 1, 4, 7] = @21) */
  for (cii=casadi_s0, rr=w18, cs=w21; cii!=casadi_s0+4; ++cii, ++cs) rr[*cii] = *cs;
  /* #70: @22 = 00 */
  /* #71: @0 = (@12<=@9) */
  w00  = (w12<=w09);
  /* #72: @9 = (@9<=@12) */
  w09  = (w09<=w12);
  /* #73: @9 = (@0+@9) */
  w09  = (w00+w09);
  /* #74: @0 = (@0/@9) */
  w00 /= w09;
  /* #75: @9 = (@7<=@11) */
  w09  = (w07<=w11);
  /* #76: @11 = (@11<=@7) */
  w11  = (w11<=w07);
  /* #77: @11 = (@9+@11) */
  w11  = (w09+w11);
  /* #78: @9 = (@9/@11) */
  w09 /= w11;
  /* #79: @11 = ones(74x1,1nz) */
  w11 = 1.;
  /* #80: {@7, NULL} = vertsplit(@11) */
  w07 = w11;
  /* #81: @11 = @7[0] */
  for (rr=(&w11), cs=(&w07)+0; cs!=(&w07)+1; cs+=1) *rr++ = *cs;
  /* #82: @9 = (@9*@11) */
  w09 *= w11;
  /* #83: @0 = (@0*@9) */
  w00 *= w09;
  /* #84: @4 = (@4*@0) */
  w04 *= w00;
  /* #85: @0 = (@2*@4) */
  w00  = (w02*w04);
  /* #86: @9 = (-@0) */
  w09 = (- w00 );
  /* #87: @13 = (@13*@4) */
  w13 *= w04;
  /* #88: @15 = (@15*@4) */
  w15 *= w04;
  /* #89: @14 = (@14*@15) */
  w14 *= w15;
  /* #90: @16 = (@16*@4) */
  w16 *= w04;
  /* #91: @14 = (@14+@16) */
  w14 += w16;
  /* #92: @13 = (@13+@14) */
  w13 += w14;
  /* #93: @13 = (@2*@13) */
  w13  = (w02*w13);
  /* #94: @23 = vertcat(@22, @0, @9, @13) */
  rr=w23;
  *rr++ = w00;
  *rr++ = w09;
  *rr++ = w13;
  /* #95: @24 = @23[:3] */
  for (rr=w24, cs=w23+0; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #96: (@18[2:11:3] = @24) */
  for (rr=w18+2, cs=w24; rr!=w18+11; rr+=3) *rr = *cs++;
  /* #97: @3 = ones(74x1,2nz) */
  casadi_fill(w03, 2, 1.);
  /* #98: {NULL, @5} = vertsplit(@3) */
  casadi_copy(w03, 2, w05);
  /* #99: @0 = @5[0] */
  for (rr=(&w00), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #100: @0 = (@2*@0) */
  w00  = (w02*w00);
  /* #101: @0 = (-@0) */
  w00 = (- w00 );
  /* #102: @9 = @5[1] */
  for (rr=(&w09), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #103: @2 = (@2*@9) */
  w02 *= w09;
  /* #104: @2 = (-@2) */
  w02 = (- w02 );
  /* #105: @5 = vertcat(@22, @0, @2, @22) */
  rr=w05;
  *rr++ = w00;
  *rr++ = w02;
  /* #106: @3 = @5[:2] */
  for (rr=w03, cs=w05+0; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #107: (@18[3:9:3] = @3) */
  for (rr=w18+3, cs=w03; rr!=w18+9; rr+=3) *rr = *cs++;
  /* #108: output[1][0] = @18 */
  casadi_copy(w18, 9, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int narx_disc_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int narx_disc_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real narx_disc_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* narx_disc_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* narx_disc_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* narx_disc_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* narx_disc_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 251;
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 251*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
