/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) narx_disc_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[81] = 
  {74, 74, 0, 2, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 0, 1, 0,
  1};
static const casadi_int casadi_s1[3] = {72, 1, 1};
static const casadi_int casadi_s2[3] = {2, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[3] = {0, 0, 1};

/* narx_disc_cost_y_hess:(i0[72],i1[2],i2[0],i3[4],i4[],i5[2])->(o0[74x74,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, *w01=w+4, w02, *w03=w+7, w04, w05, w06, w07, w08, *w09=w+14, w10;
  casadi_real w11, w12, w13, *w14=w+22;
  const casadi_real *cs;
  /* #0: @0 = zeros(74x74,4nz) */
  casadi_clear(w00, 4);
  /* #1: @1 = zeros(2x1) */
  casadi_clear(w01, 2);
  /* #2: @2 = 0 */
  w02 = 0.;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 2, w03);
  /* #4: @4 = @3[1] */
  for (rr=(&w04), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #5: @5 = (@2<=@4) */
  w05  = (w02<=w04);
  /* #6: @6 = (@4<=@2) */
  w06  = (w04<=w02);
  /* #7: @6 = (@5+@6) */
  w06  = (w05+w06);
  /* #8: @5 = (@5/@6) */
  w05 /= w06;
  /* #9: @4 = fmax(@4,@2) */
  w04  = casadi_fmax(w04,w02);
  /* #10: @6 = 1 */
  w06 = 1.;
  /* #11: @7 = (@4<=@6) */
  w07  = (w04<=w06);
  /* #12: @4 = (@6<=@4) */
  w04  = (w06<=w04);
  /* #13: @4 = (@7+@4) */
  w04  = (w07+w04);
  /* #14: @7 = (@7/@4) */
  w07 /= w04;
  /* #15: @4 = 0.7 */
  w04 = 6.9999999999999996e-01;
  /* #16: @8 = 0.316228 */
  w08 = 3.1622776601683794e-01;
  /* #17: @9 = input[3][0] */
  casadi_copy(arg[3], 4, w09);
  /* #18: {NULL, NULL, NULL, @10} = vertsplit(@9) */
  w10 = w09[3];
  /* #19: @8 = (@8*@10) */
  w08 *= w10;
  /* #20: @10 = -0.00719408 */
  w10 = -7.1940846644190657e-03;
  /* #21: @11 = @3[0] */
  for (rr=(&w11), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #22: @12 = fmax(@11,@2) */
  w12  = casadi_fmax(w11,w02);
  /* #23: @13 = (@12<=@6) */
  w13  = (w12<=w06);
  /* #24: @6 = (@6<=@12) */
  w06  = (w06<=w12);
  /* #25: @6 = (@13+@6) */
  w06  = (w13+w06);
  /* #26: @13 = (@13/@6) */
  w13 /= w06;
  /* #27: @6 = (@2<=@11) */
  w06  = (w02<=w11);
  /* #28: @11 = (@11<=@2) */
  w11  = (w11<=w02);
  /* #29: @11 = (@6+@11) */
  w11  = (w06+w11);
  /* #30: @6 = (@6/@11) */
  w06 /= w11;
  /* #31: @14 = ones(74x1,73nz) */
  casadi_fill(w14, 73, 1.);
  /* #32: {@11, NULL} = vertsplit(@14) */
  w11 = w14[0];
  /* #33: @2 = @11[0] */
  for (rr=(&w02), cs=(&w11)+0; cs!=(&w11)+1; cs+=1) *rr++ = *cs;
  /* #34: @2 = (@6*@2) */
  w02  = (w06*w02);
  /* #35: @2 = (@13*@2) */
  w02  = (w13*w02);
  /* #36: @2 = (@4*@2) */
  w02  = (w04*w02);
  /* #37: @11 = (@10*@2) */
  w11  = (w10*w02);
  /* #38: @11 = (@8*@11) */
  w11  = (w08*w11);
  /* #39: @2 = (@8*@2) */
  w02  = (w08*w02);
  /* #40: @2 = (@10*@2) */
  w02  = (w10*w02);
  /* #41: @11 = (@11+@2) */
  w11 += w02;
  /* #42: @11 = (@4*@11) */
  w11  = (w04*w11);
  /* #43: @2 = (@7*@11) */
  w02  = (w07*w11);
  /* #44: @2 = (@5*@2) */
  w02  = (w05*w02);
  /* #45: @3 = @1; (@3[1] += @2) */
  casadi_copy(w01, 2, w03);
  for (rr=w03+1, cs=(&w02); rr!=w03+2; rr+=1) *rr += *cs++;
  /* #46: @11 = (@13*@11) */
  w11  = (w13*w11);
  /* #47: @11 = (@6*@11) */
  w11  = (w06*w11);
  /* #48: (@3[0] += @11) */
  for (rr=w03+0, cs=(&w11); rr!=w03+1; rr+=1) *rr += *cs++;
  /* #49: (@0[:4:2] = @3) */
  for (rr=w00+0, cs=w03; rr!=w00+4; rr+=2) *rr = *cs++;
  /* #50: @11 = ones(74x1,1nz) */
  w11 = 1.;
  /* #51: {@2, NULL} = vertsplit(@11) */
  w02 = w11;
  /* #52: @11 = @2[0] */
  for (rr=(&w11), cs=(&w02)+0; cs!=(&w02)+1; cs+=1) *rr++ = *cs;
  /* #53: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #54: @11 = (@7*@11) */
  w11  = (w07*w11);
  /* #55: @11 = (@4*@11) */
  w11  = (w04*w11);
  /* #56: @2 = (@10*@11) */
  w02  = (w10*w11);
  /* #57: @2 = (@8*@2) */
  w02  = (w08*w02);
  /* #58: @8 = (@8*@11) */
  w08 *= w11;
  /* #59: @10 = (@10*@8) */
  w10 *= w08;
  /* #60: @2 = (@2+@10) */
  w02 += w10;
  /* #61: @4 = (@4*@2) */
  w04 *= w02;
  /* #62: @7 = (@7*@4) */
  w07 *= w04;
  /* #63: @5 = (@5*@7) */
  w05 *= w07;
  /* #64: (@1[1] += @5) */
  for (rr=w01+1, cs=(&w05); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #65: @13 = (@13*@4) */
  w13 *= w04;
  /* #66: @6 = (@6*@13) */
  w06 *= w13;
  /* #67: (@1[0] += @6) */
  for (rr=w01+0, cs=(&w06); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #68: (@0[1:5:2] = @1) */
  for (rr=w00+1, cs=w01; rr!=w00+5; rr+=2) *rr = *cs++;
  /* #69: @9 = @0' */
  casadi_trans(w00,casadi_s0, w09, casadi_s0, iw);
  /* #70: output[0][0] = @9 */
  casadi_copy(w09, 4, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int narx_disc_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int narx_disc_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real narx_disc_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* narx_disc_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* narx_disc_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* narx_disc_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* narx_disc_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 75;
  if (sz_w) *sz_w = 95;
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 75*sizeof(casadi_int);
  if (sz_w) *sz_w = 95*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
