/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) narx_disc_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 4, 7};
static const casadi_int casadi_s1[3] = {72, 1, 1};
static const casadi_int casadi_s2[3] = {2, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[3] = {4, 1, 1};
static const casadi_int casadi_s6[15] = 
  {74, 4, 0, 1, 4, 7, 8, 2,
  0, 1, 3, 0, 1, 4, 7};
static const casadi_int casadi_s7[3] = {4, 0, 1};

static const casadi_real casadi_zeros[72] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* narx_disc_cost_y_fun_jac_ut_xt:(i0[72],i1[2],i2[0],i3[],i4[2])->(o0[4],o1[74x4,8nz],o2[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w02, *w03=w+74, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, *w15=w+87, *w16=w+95, *w17=w+166, *w18=w+236, *w20=w+240;
  const casadi_int *cii;
  const casadi_real *cs, *wr01;
  /* #0: @0 = 2.23607 */
  w00 = 2.2360679774997898e+00;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[0] */
  w02 = wr01[0];
  /* #3: @3 = input[4][0] */
  casadi_copy(arg[4], 2, w03);
  /* #4: @4 = @3[0] */
  for (rr=(&w04), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #7: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #8: @2 = 0.316228 */
  w02 = 3.1622776601683794e-01;
  /* #9: @4 = 0.7 */
  w04 = 6.9999999999999996e-01;
  /* #10: @3 = input[1][0] */
  casadi_copy(arg[1], 2, w03);
  /* #11: @5 = @3[0] */
  for (rr=(&w05), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #12: @6 = 0 */
  w06 = 0.;
  /* #13: @7 = fmax(@5,@6) */
  w07  = casadi_fmax(w05,w06);
  /* #14: @8 = 1 */
  w08 = 1.;
  /* #15: @9 = fmin(@7,@8) */
  w09  = casadi_fmin(w07,w08);
  /* #16: @10 = @3[1] */
  for (rr=(&w10), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #17: @11 = fmax(@10,@6) */
  w11  = casadi_fmax(w10,w06);
  /* #18: @12 = fmin(@11,@8) */
  w12  = casadi_fmin(w11,w08);
  /* #19: @13 = (@9+@12) */
  w13  = (w09+w12);
  /* #20: @13 = (@4*@13) */
  w13  = (w04*w13);
  /* #21: @14 = @1[1] */
  w14 = wr01[1];
  /* #22: @13 = (@13-@14) */
  w13 -= w14;
  /* #23: @13 = (@2*@13) */
  w13  = (w02*w13);
  /* #24: output[0][1] = @13 */
  if (res[0]) res[0][1] = w13;
  /* #25: @9 = (@9-@12) */
  w09 -= w12;
  /* #26: @9 = (@4*@9) */
  w09  = (w04*w09);
  /* #27: @12 = @1[2] */
  w12 = wr01[2];
  /* #28: @9 = (@9-@12) */
  w09 -= w12;
  /* #29: @9 = (@2*@9) */
  w09  = (w02*w09);
  /* #30: output[0][2] = @9 */
  if (res[0]) res[0][2] = w09;
  /* #31: @9 = @1[5] */
  w09 = wr01[5];
  /* #32: @9 = (@2*@9) */
  w09  = (w02*w09);
  /* #33: output[0][3] = @9 */
  if (res[0]) res[0][3] = w09;
  /* #34: @15 = zeros(74x4,8nz) */
  casadi_clear(w15, 8);
  /* #35: @16 = ones(74x1,71nz) */
  casadi_fill(w16, 71, 1.);
  /* #36: {@9, @17} = vertsplit(@16) */
  w09 = w16[0];
  casadi_copy(w16+1, 70, w17);
  /* #37: @12 = @17[0] */
  for (rr=(&w12), cs=w17+0; cs!=w17+1; cs+=1) *rr++ = *cs;
  /* #38: @0 = (@0*@12) */
  w00 *= w12;
  /* #39: @12 = (@7<=@8) */
  w12  = (w07<=w08);
  /* #40: @7 = (@8<=@7) */
  w07  = (w08<=w07);
  /* #41: @7 = (@12+@7) */
  w07  = (w12+w07);
  /* #42: @12 = (@12/@7) */
  w12 /= w07;
  /* #43: @7 = (@6<=@5) */
  w07  = (w06<=w05);
  /* #44: @5 = (@5<=@6) */
  w05  = (w05<=w06);
  /* #45: @5 = (@7+@5) */
  w05  = (w07+w05);
  /* #46: @7 = (@7/@5) */
  w07 /= w05;
  /* #47: @5 = @9[0] */
  for (rr=(&w05), cs=(&w09)+0; cs!=(&w09)+1; cs+=1) *rr++ = *cs;
  /* #48: @7 = (@7*@5) */
  w07 *= w05;
  /* #49: @12 = (@12*@7) */
  w12 *= w07;
  /* #50: @12 = (@4*@12) */
  w12  = (w04*w12);
  /* #51: @12 = (@2*@12) */
  w12  = (w02*w12);
  /* #52: @7 = @17[3] */
  for (rr=(&w07), cs=w17+3; cs!=w17+4; cs+=1) *rr++ = *cs;
  /* #53: @7 = (@2*@7) */
  w07  = (w02*w07);
  /* #54: @18 = vertcat(@0, @12, @12, @7) */
  rr=w18;
  *rr++ = w00;
  *rr++ = w12;
  *rr++ = w12;
  *rr++ = w07;
  /* #55: (@15[0, 1, 4, 7] = @18) */
  for (cii=casadi_s0, rr=w15, cs=w18; cii!=casadi_s0+4; ++cii, ++cs) rr[*cii] = *cs;
  /* #56: @19 = 00 */
  /* #57: @0 = (@11<=@8) */
  w00  = (w11<=w08);
  /* #58: @8 = (@8<=@11) */
  w08  = (w08<=w11);
  /* #59: @8 = (@0+@8) */
  w08  = (w00+w08);
  /* #60: @0 = (@0/@8) */
  w00 /= w08;
  /* #61: @8 = (@6<=@10) */
  w08  = (w06<=w10);
  /* #62: @10 = (@10<=@6) */
  w10  = (w10<=w06);
  /* #63: @10 = (@8+@10) */
  w10  = (w08+w10);
  /* #64: @8 = (@8/@10) */
  w08 /= w10;
  /* #65: @10 = ones(74x1,1nz) */
  w10 = 1.;
  /* #66: {@6, NULL} = vertsplit(@10) */
  w06 = w10;
  /* #67: @10 = @6[0] */
  for (rr=(&w10), cs=(&w06)+0; cs!=(&w06)+1; cs+=1) *rr++ = *cs;
  /* #68: @8 = (@8*@10) */
  w08 *= w10;
  /* #69: @0 = (@0*@8) */
  w00 *= w08;
  /* #70: @4 = (@4*@0) */
  w04 *= w00;
  /* #71: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #72: @0 = (-@4) */
  w00 = (- w04 );
  /* #73: @3 = vertcat(@19, @4, @0, @19) */
  rr=w03;
  *rr++ = w04;
  *rr++ = w00;
  /* #74: @20 = @3[:2] */
  for (rr=w20, cs=w03+0; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #75: (@15[2:8:3] = @20) */
  for (rr=w15+2, cs=w20; rr!=w15+8; rr+=3) *rr = *cs++;
  /* #76: @20 = ones(74x1,2nz) */
  casadi_fill(w20, 2, 1.);
  /* #77: {NULL, @3} = vertsplit(@20) */
  casadi_copy(w20, 2, w03);
  /* #78: @4 = @3[0] */
  for (rr=(&w04), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #79: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #80: @4 = (-@4) */
  w04 = (- w04 );
  /* #81: @0 = @3[1] */
  for (rr=(&w00), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #82: @2 = (@2*@0) */
  w02 *= w00;
  /* #83: @2 = (-@2) */
  w02 = (- w02 );
  /* #84: @3 = vertcat(@19, @4, @2, @19) */
  rr=w03;
  *rr++ = w04;
  *rr++ = w02;
  /* #85: @20 = @3[:2] */
  for (rr=w20, cs=w03+0; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #86: (@15[3:9:3] = @20) */
  for (rr=w15+3, cs=w20; rr!=w15+9; rr+=3) *rr = *cs++;
  /* #87: output[1][0] = @15 */
  casadi_copy(w15, 8, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int narx_disc_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int narx_disc_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real narx_disc_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* narx_disc_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* narx_disc_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* narx_disc_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* narx_disc_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 242;
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 242*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
