/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) narx_disc_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {72, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};

static const casadi_real casadi_zeros[72] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* narx_disc_cost_y_0_fun:(i0[72],i1[2],i2[0],i3[],i4[2])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, w2, *w3=w+74, w4, *w5=w+77, w6, w7, w8;
  const casadi_real *cs, *wr1;
  /* #0: @0 = 2.23607 */
  w0 = 2.2360679774997898e+00;
  /* #1: @1 = input[0][0] */
  wr1 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[0] */
  w2 = wr1[0];
  /* #3: @3 = input[4][0] */
  casadi_copy(arg[4], 2, w3);
  /* #4: @4 = @3[0] */
  for (rr=(&w4), cs=w3+0; cs!=w3+1; cs+=1) *rr++ = *cs;
  /* #5: @2 = (@2-@4) */
  w2 -= w4;
  /* #6: @0 = (@0*@2) */
  w0 *= w2;
  /* #7: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #8: @0 = 0.316228 */
  w0 = 3.1622776601683794e-01;
  /* #9: @2 = 0.7 */
  w2 = 6.9999999999999996e-01;
  /* #10: @5 = input[1][0] */
  casadi_copy(arg[1], 2, w5);
  /* #11: @4 = @5[0] */
  for (rr=(&w4), cs=w5+0; cs!=w5+1; cs+=1) *rr++ = *cs;
  /* #12: @6 = 0 */
  w6 = 0.;
  /* #13: @4 = fmax(@4,@6) */
  w4  = casadi_fmax(w4,w6);
  /* #14: @7 = 1 */
  w7 = 1.;
  /* #15: @4 = fmin(@4,@7) */
  w4  = casadi_fmin(w4,w7);
  /* #16: @8 = @5[1] */
  for (rr=(&w8), cs=w5+1; cs!=w5+2; cs+=1) *rr++ = *cs;
  /* #17: @8 = fmax(@8,@6) */
  w8  = casadi_fmax(w8,w6);
  /* #18: @8 = fmin(@8,@7) */
  w8  = casadi_fmin(w8,w7);
  /* #19: @7 = (@4+@8) */
  w7  = (w4+w8);
  /* #20: @7 = (@2*@7) */
  w7  = (w2*w7);
  /* #21: @6 = @1[1] */
  w6 = wr1[1];
  /* #22: @6 = (@7-@6) */
  w6  = (w7-w6);
  /* #23: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #24: output[0][1] = @6 */
  if (res[0]) res[0][1] = w6;
  /* #25: @4 = (@4-@8) */
  w4 -= w8;
  /* #26: @2 = (@2*@4) */
  w2 *= w4;
  /* #27: @4 = @1[2] */
  w4 = wr1[2];
  /* #28: @2 = (@2-@4) */
  w2 -= w4;
  /* #29: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #30: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #31: @2 = -0.000431337 */
  w2 = -4.3133721733220226e-04;
  /* #32: @4 = -0.00299963 */
  w4 = -2.9996288193116886e-03;
  /* #33: @4 = (@4*@7) */
  w4 *= w7;
  /* #34: @2 = (@2+@4) */
  w2 += w4;
  /* #35: @4 = -0.00719408 */
  w4 = -7.1940846644190657e-03;
  /* #36: @4 = (@4*@7) */
  w4 *= w7;
  /* #37: @4 = (@4*@7) */
  w4 *= w7;
  /* #38: @2 = (@2+@4) */
  w2 += w4;
  /* #39: @4 = @3[1] */
  for (rr=(&w4), cs=w3+1; cs!=w3+2; cs+=1) *rr++ = *cs;
  /* #40: @2 = (@2-@4) */
  w2 -= w4;
  /* #41: @0 = (@0*@2) */
  w0 *= w2;
  /* #42: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void narx_disc_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int narx_disc_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int narx_disc_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real narx_disc_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* narx_disc_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* narx_disc_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* narx_disc_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* narx_disc_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 82;
  return 0;
}

CASADI_SYMBOL_EXPORT int narx_disc_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 82*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
